export const LOGIN_WITH_GOOGLE = 'LOGIN_WITH_GOOGLE';
export const LOGIN_SUCCESSFUL = 'LOGIN_SUCCESSFUL';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';
export const LOGOUT = 'LOGOUT';

export const LOAD_ADMIN_USER = 'LOAD_ADMIN_USER';
export const ADMIN_USER_LOADED = 'ADMIN_USER_LOADED';