export const LOGIN_WITH_GOOGLE = 'LOGIN_WITH_GOOGLE';
export const LOGIN_SUCCESSFUL = 'LOGIN_SUCCESSFUL';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';
export const LOGOUT = 'LOGOUT';

export const LOAD_ADMIN_USER = 'LOAD_ADMIN_USER';
export const ADMIN_USER_LOADED = 'ADMIN_USER_LOADED';

export const ADD_VOTING = 'ADD_VOTING';
export const VOTING_ADDED = 'VOTING_ADDED';
export const VOTING_ADDED_ERROR = 'VOTING_ADDED_ERROR';

export const REMOVE_VOTING = 'REMOVE_VOTING';
export const VOTING_REMOVED = 'VOTING_REMOVED';
export const REMOVE_VOTING_ERROR = 'VOTING_REMOVED';