export const LOGIN_WITH_GOOGLE = 'LOGIN_WITH_GOOGLE';
export const LOGIN_SUCCESSFUL = 'LOGIN_SUCCESSFUL';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';
export const LOGOUT = 'LOGOUT';

export const LOAD_VOTINGS = 'LOAD_VOTINGS';
export const VOTINGS_LOADED = 'VOTINGS_LOADED';
export const LOAD_VOTINGS_ERROR = 'LOAD_VOTINGS_ERROR';

export const LOAD_VOTING_ITEMS = 'LOAD_VOTING_ITEMS';
export const VOTING_ITEMS_LOADED = 'VOTING_ITEMS_LOADED';

export const ADD_VOTING = 'ADD_VOTING';
export const VOTING_ADDED = 'VOTING_ADDED';
export const VOTING_ADDED_ERROR = 'VOTING_ADDED_ERROR';

export const ADD_VOTING_ITEM = 'ADD_VOTING_ITEM';
export const VOTING_ITEM_ADDED = 'VOTING_ITEM_ADDED';
export const VOTING_ITEM_ADDED_ERROR = 'VOTING_ITEM_ADDED_ERROR';

export const REMOVE_VOTING_ITEM = 'REMOVE_VOTING_ITEM';
export const VOTING_ITEM_REMOVED = 'VOTING_ITEM_REMOVED';
export const VOTING_ITEM_REMOVED_ERROR = 'VOTING_ITEM_REMOVED_ERROR';

export const ADD_RATING = 'ADD_RATING';
export const RATING_ADDED = 'RATING_ADDED';
export const ADD_RATING_ERROR = 'ADD_RATING_ERROR';

export const REMOVE_VOTING = 'REMOVE_VOTING';
export const VOTING_REMOVED = 'VOTING_REMOVED';
export const REMOVE_VOTING_ERROR = 'VOTING_REMOVED';
